### ISSUE TITLE
Location of (Spanish) translations for auxiliary files

### ISSUE THREAD

**Issue by olemis** [Carpentries-ES/board#14]
After reading the docs it is clear to me that translations for files located at `_episodes` folder should be included in `_episodes_es` . Nonetheless it is not clear to me what path translations for auxiliary files (e.g. Carpentries-ES/git-novice#14 ) should be stored at .

Cc @rgaiacs .

**Comment by rgaiacs** [comment]
My suggestion was to move all auxiliar files to `XX/` folder where `XX` is the two letter language code. For example, you would have `en/README.md`, `en/setup.md`, `en/index.md`, `en/reference.md` and similar for Spanish. Also, we could use `_episodes_en` instead of `_episodes`.

**Comment by olemis** [comment]
@rgaiacs is there consensus on this (to apply these changes right away) or should I wait until a final decision's been made ?

In my opinion at least README.md should remain in repo root folder for github and other sites be able to render project home page . But maybe there is a way to configure in Github the path to project home page . 

Option 2 : Alternatively the README.md could be a simple index forwarding to the language-specific `XX/README.md` pages . Something like 

```md
![](flag.en.png)
Welcome to the Carpentries git-novice workshop ! Please see English docs in [here](en/README.md).

![](flag.es.png)
¡ Bienvenido al taller git-novice de los Carpentries ! Para más detalles consultar [la documentación en español](es/README.md).

![](flag.fr.png)
Bienvenue au tuto git-novice des Carpentries ! Pour en savoir plus veuillez consulter [la documentation en Français](fr/README.md)

... etc
```

Option 3: could consist in sticking to the current structure, add the language index in the `README.md` file at the root folder and update that in translations.

... just ideas ...

**Comment by rgaiacs** [comment]
> is there consensus on this

**No**. We didn't make a decision about how translation was going to be organised. My preference is for https://github.com/Carpentries-ES/board/issues/12. But I should not dictate it.

> Option 2 : Alternatively the README.md could be a simple index forwarding to the language-specific XX/README.md pages . Something like

I like the idea.

**Comment by orchid00** [comment]
Calling to other comments @map0logo @agbeltran @ThinkOnData @olemis 

Would like to hear more of your thoughts and move on with this issue. 
Can we vote on the options (suggested by olemis)
1,2 and 3 from above ?
My vote goes for option 2: move the auxiliar files to the language-specific folder, which is _episodes_en

If we have 3 votes on one of the options I think with should go for that one

**Comment by map0logo** [comment]
Hi everybody,

I also vote for option 2. That is some kind of _de facto_ standard on software projects for localization purposes. There are another issues to solve around the workflow to keep in sync the translations as long as necessary, and add notes (git branches or tags) at points where divergences occur. For instance, for using "alicia" instead of "elle", but could be more significant ones.

Any decision involves a great deal of planning. Better starting than on the run.

**Comment by orchid00** [comment]
@map0logo I think @dledezma has changed all the Alicia for Nelle as far as I am aware

**Comment by olemis** [comment]
@orchid00 said
> My vote goes for option 2: move the auxiliar files to the language-specific folder, which is _episodes_en

+1

**Comment by orchid00** [comment]
Thank you! 

I think this is consensus Option 2: move the auxiliary files to the language-specific folder, which is _episodes_en 
I can help doing this for git, shell and R-gapminder

**Comment by olemis** [comment]
> I can help doing this for git, shell and R-gapminder

Thanks ! I'll wait for you to do this , and continue from there .

**Comment by rgaiacs** [comment]
> I can help doing this for git, shell and R-gapminder

Can we have a reference implementation before start changing some of the repos? Please send a pull request to https://github.com/swcarpentry/lesson-example.

**Comment by orchid00** [comment]
@olemis @rgaiacs @map0logo @agbeltran @jmbarrios 

git aux files moved or created in
https://github.com/Carpentries-ES/git-novice/tree/gh-pages/_episodes_es
README.md, translated
index.md, translated
reference.md, to be translated

Is there other extra file to be translated?

**Comment by orchid00** [comment]
and setup.md too

**Comment by rgaiacs** [comment]
I think that you missed https://github.com/swcarpentry/git-novice/tree/gh-pages/_extras.

**Comment by orchid00** [comment]
noted, will do

**Comment by orchid00** [comment]
just to confirm those files will go under _episodes_es and not under _episodes_es/extras
can someone correct me please, if I am wrong?

**Comment by rgaiacs** [comment]
> just to confirm those files will go under _episodes_es

They can't because it will probably break a for loop in the template.

> and not under _episodes_es/extras

I think it will also break the template.

**Comment by orchid00** [comment]
I hand in to others here to decide.

**Comment by ErinBecker** [comment]
@rgaiacs and all,

I appreciate the complexity of the situation and that we would like to make the best decision possible here in order to make it easier to carry this work forward into the future as other changes get made. However, I also appreciate that there has been a lot of work done on translating the lessons and I don't want the publication of those lessons to continue to be stalled because we're prematurely optimizing the relationship of the Spanish vs English lesson files. 

What we need at this point is a solution that works to get the existing lesson translations published and doesn't actively prevent subsequent updates. From the conversation above, it appears that there have been several solutions presented, and that a consensus was reached, but that it wasn't clear how to implement that consensus. 

It seems that we have a path forward, and I'm happy to implement that path (and it appears that @olemis is also willing to do so). It seems that @orchid00 has also tried to implement the suggested changes and was told that this implementation would break the template. 

@rgaiacs - since you are the one with the most experience with the template, and a deep understanding of how it works, it will be very useful for you to give a clear communication about what steps are needed to implement the proposed solution above. For example, from your comment:

>> My suggestion was to move all auxiliar files to XX/ folder where XX is the two letter language code. For example, you would have en/README.md, en/setup.md, en/index.md, en/reference.md and similar for Spanish. Also, we could use _episodes_en instead of _episodes.

it appears that the structure of the repository should be like this:

>> git-novice/en/setup.md
git-novice/en/index.md
git-novice/en/reference.md

>> git-novice/es/setup.md
git-novice/es/index.md
git-novice/es/reference.md

But it isn't clear from this where the episode files should go. 

Should it be like A:

>> git-novice/en/_episodes
git-novice/en/_episodes_rmd

>> git-novice/es/_episodes
git-novice/es/_episodes_rmd

Or like B:

>> git-novice/en/_episodes_en
git-novice/en/_episodes_rmd

>> git-novice/es/_episodes_es
git-novice/es/_episodes_rmd

Or like some other option?

Also, in this new organization, will there be the following subdirectories, and if so, where will they be located?

>> _extras/
_includes/
_layouts/

If we can get clarification on these issues, we can re-organize these files and be one step closer to publication. 

Thanks again all for the discussion and the many hours of work already on this project.

**Comment by ErinBecker** [comment]
@rgaiacs - I see your very detailed explanations at https://github.com/Carpentries-ES/board/issues/10 and https://github.com/Carpentries-ES/board/issues/11. These look like they will answer all of my questions so I am reading them in detail now.

**Comment by rgaiacs** [comment]
I'm closing this because for now we will be doing the translation on their own repository.
